version: '3.8'
services:
  php:
    build: .

    container_name: website_prof_staging

    ports:
    - "127.0.0.1:9003:9000"

    volumes:
      - /var/www/html/website_prof_staging:/var/www/html
      - /mnt/hdd2tb/uploads_lms_staging:/var/www/html/uploads

    working_dir: /var/www/html

    restart: unless-stopped
    environment:
      APP_ENV: staging
      FONNTE_TOKEN: ${FONNTE_TOKEN}
    networks:          
      - sija_net
  db:
    image: mariadb:11

    container_name: website_prof_db_staging

    restart: unless-stopped
    
    ports:
        - "127.0.0.1:3310:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_STAGING}
      MYSQL_DATABASE: ${MYSQL_DATABASE_STAGING}
      MYSQL_USER: ${MYSQL_USER_STAGING}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_STAGING}

    volumes:
      - mariadb_data:/var/lib/mysql
    
    networks: 
      - sija_net
volumes:
  mariadb_data:
networks:             
  sija_net:
    driver: bridge